pool:
    vmImage: 'Ubuntu 16.04'

variables:
    Version: '3.0.$(Build.BuildId)'

steps:
    - task: UseDotNet@2
      inputs:
          packageType: sdk
          version: 3.0.100-preview6-012264
          includePreviewVersions: true
    - task: DotNetCoreCLI@2
      inputs:
          command: restore
          projects: '**/*.csproj'
          feedsToUse: 'select'
          verbosityRestore: 'minimal'
          vstsFeed: 'BioEngine'

    - task: DotNetCoreCLI@2
      inputs:
          command: custom
          custom: publish
          publishWebProjects: false
          zipAfterPublish: false
          modifyOutputPath: false
          arguments: '--no-restore -c Release --output ./publish'
          projects: '**/*.csproj'

    - script: |
          docker build -f src/BioEngine.BRC.Importer/Dockerfile ./publish -t biowareru/bioengine-brc-importer:$(Version)
      displayName: 'build docker image'

    - script: |
          docker login -u $(dockerId) -p $(dockerPswd)
      displayName: 'login to docker hub'

    - script: |
          docker push biowareru/bioengine-brc-importer:$(Version)
      displayName: 'push image to docker hub'
    
